server:
  port: 8090

spring:
  application:
    name: restaurants

  # MongoDB Configuration
  data:
    mongodb:
      uri: mongodb+srv://root:1234@fod-restaurant.9yjieml.mongodb.net/
      database: fod-restaurant
      username: root
      password: 1234

  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
